version: '3'
name: docker_alpine_nginx_angular
services:
  angular:
    container_name: docker_alpine_nginx_angular
    image: mochrira/angular:15.2.3-nginx
    build: 
      context: ./
      dockerfile: dockerfile
    volumes:
      - ./example:/home/node/app
      - docker_ng_data:/var/www/html
    ports:
      - 8080:80
    networks:
      - environment
    environment:
      - PRODUCTION=NO
      - REINSTALL_MODULES=YES
      - NG_CONFIGURATION=development
      - NG_REBUILD=YES
      
volumes:
  docker_ng_data:
    name: docker_ng_data

networks:
  environment:
    name: environment
    external: true