version: '3'
name: docker_alpine_nginx_angular
services:
  angular:
    container_name: docker_alpine_nginx_angular
    image: mochrira/angular:15.2.3-nginx
    build: 
      context: ./
      dockerfile: dockerfile
    volumes:
      - ./example:/home/node/app
    ports:
      - 8080:80
    networks:
      - environment
    environment:
      - PRODUCTION=$PRODUCTION
      - REINSTALL_MODULES=$REINSTALL_MODULES
      - NG_CONFIGURATION=$NG_CONFIGURATION
      - NG_REBUILD=$NG_REBUILD
      
networks:
  environment:
    name: environment
    external: true