FROM node:lts-alpine
RUN apk update
RUN apk add --no-cache nginx sudo

RUN mkdir -p /etc/sudoers.d
RUN echo "node ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/node
RUN chmod 0440 /etc/sudoers.d/node

RUN echo \
$'server { \n\
    listen 80 default_server; \n\
    listen [::]:80 default_server; \n\
    try_files $uri $uri/ /index.html; \n\
\n\
    root /home/node/app/dist; \n\
    index index.html; \n\
}' > /etc/nginx/http.d/default.conf

RUN npm install -g @angular/cli@15.2.3
RUN npm cache verify

RUN rm -f /var/log/nginx/access.log
RUN rm -f /var/log/nginx/error.log
RUN ln -s /dev/stdout /var/log/nginx/access.log
RUN ln -s /dev/stderr /var/log/nginx/error.log

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER node
WORKDIR /home/node/app
ENTRYPOINT [ "/bin/sh", "/entrypoint.sh" ]