FROM node:lts-alpine

RUN apk update && apk add --no-cache nginx sudo \
    && mkdir -p /etc/sudoers.d \
    && echo "node ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/node \
    && chmod 0440 /etc/sudoers.d/node

RUN npm install -g @angular/cli@16.2 \
    && npm cache clean --force \
    && npm cache verify

RUN rm -f /var/log/nginx/* \
    && ln -s /dev/stdout /var/log/nginx/access.log \
    && ln -s /dev/stderr /var/log/nginx/error.log

COPY default.conf /etc/nginx/http.d/default.conf
COPY entrypoint.sh /entrypoint.sh

USER node
WORKDIR /home/node/app
ENTRYPOINT [ "/bin/sh", "/entrypoint.sh"]